### ISSUE TITLE
求问大神如何将这个react-mind嵌入到react中使用啊

### ISSUE THREAD

**Issue by yuxue3923** [guimeisang/react-mind#3]
我通过使用说明安装了react-mind
同时也进行了引入
但运行报错
![image](https://user-images.githubusercontent.com/41003547/42980368-83d10d00-8c09-11e8-8cb1-fbc1d39a65f6.png)
请问大神这是什么情况呢

**Comment by dolphincici** [comment]
我也是运行不了，import xminder 会提示找不到模块

**Comment by guimeisang** [comment]
用`npm install react-mind`安装包，然后在你的react组件中引入react-mind没有用么？
