### ISSUE TITLE
What's the relation between react-mind and jsmind?

### ISSUE THREAD

**Issue by anyexinglu** [guimeisang/react-mind#4]
https://guimeisang.github.io/react-mind/example/demo1.html
http://hizzgdev.github.io/jsmind/example/1_basic.html

https://github.com/guimeisang/react-mind/blob/master/src/mind.js
https://github.com/hizzgdev/jsmind/blob/master/js/jsmind.js

related issue: https://github.com/hizzgdev/jsmind/issues/212

**Comment by hizzgdev** [comment]
@guimeisang 你好，为了避免 @anyexinglu 同学有此疑惑，建议你在 react-mind 项目中保留 jsMind 的版权声明。

以下是jsMind的版权申明，对于源码的使用几乎没有任何限制，也不影响你添加 react-mind 自己的版权声明。
https://github.com/hizzgdev/jsmind/blob/master/LICENSE

**Comment by guimeisang** [comment]
这个项目是基于jsMind改造的，为了适配react
